# Generated by Django 4.0.5 on 2022-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCurso', models.CharField(max_length=100, verbose_name='Curso')),
                ('NombreTutor', models.CharField(max_length=150)),
                ('Descripcion', models.TextField()),
                ('Link', models.CharField(max_length=150)),
                ('Platafroma', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
