# Generated by Django 4.0.5 on 2022-06-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Link',
            field=models.CharField(max_length=150, verbose_name='Enlace del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='NombreTutor',
            field=models.CharField(max_length=150, verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Platafroma',
            field=models.CharField(max_length=50, verbose_name='Plataforma'),
        ),
    ]
