# Generated by Django 4.0.5 on 2022-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_archivos_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='NombreTutor',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Platafroma',
        ),
        migrations.AddField(
            model_name='cursos',
            name='AlumnosRegistrados',
            field=models.CharField(max_length=100, null=True, verbose_name='Alumnos Registrados'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='FechaInicio',
            field=models.CharField(max_length=100, null=True, verbose_name='Fecha de Inicio'),
        ),
    ]
