# Generated by Django 4.0.5 on 2022-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_remove_cursos_link_remove_cursos_nombretutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='telefono',
            field=models.CharField(max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
